<?php
return [
    'db' => [
        'servername' => 'localhost',
        'username' => 'root',
        'password' => '',
        'dbname' => 'taxdb',
    ],
    'questions' => [
        'permanent_home' => 'Do you have a permanent home in Country A, Country B, both, or neither?',
        'vital_interests' => 'Do you have vital interests in Country A, Country B, both, or neither?',
        'habitual_abode' => 'Do you have a habitual abode in Country A, Country B, both, or neither?',
        'citizenship' => 'Are you a citizen of Country A, Country B, both, or neither?',
    ],
    'display' => [
        'case_summary_title' => 'Case Summary',
        'double_tax_treaty_title' => 'Double Tax Treaty Evaluation',
        'case_summary_for' => 'Case Summary for',
        'case_id' => 'Case ID:',
        'initial_tax_liability' => 'Initial Tax Liability:',
        'tax_question' => 'Tax Question:',
        'created_at' => 'Created At:',
        'conclusion' => 'Conclusion',
        'tax_residency' => 'Tax Residency:',
        'double_tax_residency' => 'Double Tax Residency:',
        'submitted_answers' => 'Submitted Answers',
        'no_answers_submitted' => 'No answers submitted yet.',
        'double_tax_treaty_answers' => 'Double Tax Treaty Answers',
        'pending' => 'Pending',
        'determine_tax_residency' => 'Determine Tax Residency for',
        'access_denied' => 'Access denied. You must be a resident of Tax B to access this page.',
        'next' => 'Next',
        'country_a' => 'Country A',
        'country_b' => 'Country B',
        'both' => 'Both Countries',
        'neither' => 'Neither',
        'tax_liability_clarification' => 'Tax Liability Clarification',
        'case_name' => 'Case Name:',
        'initial_tax_status' => 'Initial Tax Status:',
        'create_case' => 'Create Case',
        'previous_cases' => 'Previous Cases',
        'view_summary' => 'View Summary',
        'initial_clarification' => 'Initial clarification',
        'double_tax_treaty' => 'Double Tax Treaty',
        'please_answer_questions' => 'Please answer the following questions:',
    ],
    'translated_questions' => [
        'permanent_home' => 'Permanent Home',
        'vital_interests' => 'Vital Interests',
        'habitual_abode' => 'Habitual Abode',
        'citizenship' => 'Citizenship',
    ],
    'translated_answers' => [
        'yes' => 'Yes',
        'no' => 'No',
        'country_a' => 'Country A',
        'country_b' => 'Country B',
        'both' => 'Both Countries',
        'neither' => 'Neither',
    ],
    'dynamic_form_questions' => [
        'stayPermanent' => 'Has the person taken permanent residence abroad?',
        'taxResidentA10' => 'Has the person been a tax resident in Norway for more than 10 years before moving abroad?',
        'stayA61' => 'Has the person stayed in Norway for more than 61 days in the income year?',
        'homeAccessA' => 'Has the person or their close family had access to a home in Norway?',
        'threeYearRule' => 'For each of the three years after moving abroad, has the person stayed in Norway for more than 61 days OR had access to a home in Norway in ANY of these years?',
        'residentTaxB' => 'Is the person a resident for tax purposes in the other country?',
    ],
    'dynamic_form_answers' => [
        'yes' => 'Yes',
        'no' => 'No',
    ],
];